### ISSUE TITLE
RC3: spring prints gobbledygook [aarch64]

### ISSUE THREAD

**Issue by heshpdx** [dacapobench/dacapobench#227]
This is on release candidate 3. I tried running spring on aarch64 160-core Ampere Altra, with the latest Microsoft jdk (available at https://learn.microsoft.com/en-us/java/openjdk/download)

`$ ../JAVA/jdk-17.0.8.1+1/bin/java -jar dacapo-23.9-RC3-chopin.jar -v -n 2 spring`

A lot of strange stuff is being printed out. The outcome is the same regardless of whether I pass `-v` or not. I have attached a log file; I killed the run after a few minutes since the log file was growing quickly, and this is just the first 200000 lines: [spring.aarch64.log.gz](https://github.com/dacapobench/dacapobench/files/12591788/spring.aarch64.log.gz)

**Comment by steveblackburn** [comment]
Interesting.  I've not seen this before.

~As far as I can tell, this appears to be a problem with the Microsoft JDK, or at least a bug that is specific to that JDK.~  I test against 7 jdks (openjdk, temurin, across 8 - 20), and spring (as with all other benchmarks) passes on all of these JVMs at all sizes.

However, I am (unfortunately) not testing on aarch64, nor do I test with more than 32 CPUs.  So it may be the JVM, the core count, or that you're testing on ARM.

**Comment by steveblackburn** [comment]
Could you please run with  -t 32` to cap the thread count at 32 to see if this (alone) is the issue?

**Comment by heshpdx** [comment]
I kept lowering the thread count all the way down to 1, and it still has this behavior.
Preserving stderr, we see this at the top:

```
Starting 8192 requests...
Unexpected response length. Got 67721 but expected 64928 for request GET /resources/images/pets.png, got:
?PNG
^Z
^@^@^@
IHDR^@^@^@?^@^@^@^B^@^@^@???1^@^@^@     pHYs^@^@^K^S^@^@^K^S^A^@??^X^@^@
OiCCPPhotoshop ICC profile^@^@x??SgTS?^V=???BK???KoR^U^H RB??^T?&*!     ^PJ?!??^UQ?^QEE^DESC???^C????^UQ,^L?
?^G?!?????????{?k????????>??????^G^L?H3Q5?^L?B^^^Q???????.@?
```
Looks like the problem is an incorrect image was returned, and then it decides to show me the image that it did receive 😆

**Comment by steveblackburn** [comment]
Thanks. So it seems not to relate to core count. Next will be to determine whether this is JVM-specific.

**Comment by heshpdx** [comment]
I just tried the java that is default on my system, and saw the same behavior and stderr (also got 67721 bytes). My system java is the following:

```
openjdk 11.0.20.1 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode)
```

**Comment by steveblackburn** [comment]
Same platform, aarch64?

**Comment by heshpdx** [comment]
Yes, aarch64

**Comment by caizixian** [comment]
I didn't reproduce the problem on Cavium ThunderX CN8890, Ubuntu 18.04, Temurin-17.0.8.1+1 aarch64 

```
./jdk-17.0.8.1+1/bin/java -jar ./dacapo-23.9-RC3-chopin.jar -n 2 spring
Using scaled threading model. 48 processors detected, 48 threads used to drive the workload, in a possible range of [1,unlimited]
Version: springboot 2.7.3 petclinic git-9ecdc11 h2 2.1.214 hibernate 5.6.10 tomcat 9.0.65 (use -p to print nominal benchmark stats)
Loaded 8192 requests
Launching the server


              |\      _,,,--,,_
             /,`.-'`'   ._  \-;;,_
  _______ __|,4-  ) )_   .;.(__`'-'__     ___ __    _ ___ _______
 |       | '---''(_/._)-'(_\_)   |   |   |   |  |  | |   |       |
 |    _  |    ___|_     _|       |   |   |   |   |_| |   |       | __ _ _
 |   |_| |   |___  |   | |       |   |   |   |       |   |       | \ \ \ \
 |    ___|    ___| |   | |      _|   |___|   |  _    |   |      _|  \ \ \ \
 |   |   |   |___  |   | |     |_|       |   | | |   |   |     |_    ) ) ) )
 |___|   |_______| |___| |_______|_______|___|_|  |__|___|_______|  / / / /
 ==================================================================/_/_/_/

:: Built with Spring Boot :: 2.7.3


===== DaCapo 23.9-RC3-chopin spring starting warmup 1 =====
Starting 8192 requests...
Completing query batches: 100%
Completed requests
===== DaCapo 23.9-RC3-chopin spring completed warmup 1 in 10658 msec =====
===== DaCapo simple tail latency: 50% 18748 usec, 90% 127626 usec, 99% 301258 usec, 99.9% 2745554 usec, 99.99% 3101988 usec, max 3101988 usec, measured over 8192 events =====
===== DaCapo metered tail latency: 50% 1634856 usec, 90% 2925125 usec, 99% 3093626 usec, 99.9% 3216373 usec, 99.99% 3282696 usec, max 3282696 usec, measured over 8192 events =====
===== DaCapo 23.9-RC3-chopin spring starting =====
Starting 8192 requests...
Completing query batches: 100%
Completed requests
===== DaCapo 23.9-RC3-chopin spring PASSED in 6878 msec =====
===== DaCapo simple tail latency: 50% 18238 usec, 90% 105030 usec, 99% 221117 usec, 99.9% 288198 usec, 99.99% 378098 usec, max 378098 usec, measured over 8192 events =====
===== DaCapo metered tail latency: 50% 26059 usec, 90% 111619 usec, 99% 232302 usec, 99.9% 301842 usec, 99.99% 378098 usec, max 378098 usec, measured over 8192 events =====
```

**Comment by steveblackburn** [comment]
Summarizing:

- insensitive to `-t` (which controls client thread count, not necessarily server thread count)
- aarch64 only
  - FAIL
    - aarch64 160-core Ampere Altra, Microsoft  OpenJDK 17.0.8.1 LTS (?)
    - openjdk 11.0.20.1 2023-08-24
  - PASS
    - Cavium ThunderX CN8890, Ubuntu 18.04, Temurin-17.0.8.1+1 aarch64

**Comment by heshpdx** [comment]
Here are some new data points, all with this cmdline, all failing with the same signature as above.

`java -jar dacapo-23.9-RC3-chopin.jar -v -n 2 -preserve -t 1 spring`

FAIL

- Huawei Taishan (aarch64, 96 cores), openjdk 11
- Huawei Taishan (aarch64), msjdk 17
- Cavium ThunderX2 (aarch64, 56 cores w/2 threads == 112 threads), openjdk 1.8.0_232
- Cavium ThunderX2 (aarch64), msjdk 17
- Qualcomm Centriq 2452 (aarch64, 46 cores), openjdk 17.0.8.1
- Qualcomm Centriq 2452 (aarch64), msjdk 17

**Comment by caizixian** [comment]
I saw a different issue on AMD EPYC 9534
```console
$ /usr/lib/jvm/temurin-17-jdk-amd64/bin/java -jar dacapo-23.9-RC3-chopin.jar -n 2 -preserve spring
Using scaled threading model. 128 processors detected, 128 threads used to drive the workload, in a possible range of [1,unlimited]
Version: springboot 2.7.3 petclinic git-9ecdc11 h2 2.1.214 hibernate 5.6.10 tomcat 9.0.65 (use -p to print nominal benchmark stats)
Loaded 8192 requests
Launching the server


              |\      _,,,--,,_
             /,`.-'`'   ._  \-;;,_
  _______ __|,4-  ) )_   .;.(__`'-'__     ___ __    _ ___ _______
 |       | '---''(_/._)-'(_\_)   |   |   |   |  |  | |   |       |
 |    _  |    ___|_     _|       |   |   |   |   |_| |   |       | __ _ _
 |   |_| |   |___  |   | |       |   |   |   |       |   |       | \ \ \ \
 |    ___|    ___| |   | |      _|   |___|   |  _    |   |      _|  \ \ \ \
 |   |   |   |___  |   | |     |_|       |   | | |   |   |     |_    ) ) ) )
 |___|   |_______| |___| |_______|_______|___|_|  |__|___|_______|  / / / /
 ==================================================================/_/_/_/

:: Built with Spring Boot :: 2.7.3


===== DaCapo 23.9-RC3-chopin spring starting warmup 1 =====
Starting 8192 requests...
Completing query batches: 100%
Completed requests
Digest validation failed for stdout.log, expecting 0x3d667eb33ec98f18caf9fb13954b49402d64f249 found 0xbe39d43d8496ce8f556ab54870e656796eb16952
===== DaCapo 23.9-RC3-chopin spring FAILED warmup =====
===== DaCapo simple tail latency: 50% 12233 usec, 90% 245674 usec, 99% 568638 usec, 99.9% 856726 usec, 99.99% 1000410 usec, max 1000410 usec, measured over 8192 events =====
===== DaCapo metered tail latency: 50% 304159 usec, 90% 597947 usec, 99% 827733 usec, 99.9% 918576 usec, 99.99% 1090355 usec, max 1090355 usec, measured over 8192 events =====
===== DaCapo 23.9-RC3-chopin spring starting =====
Starting 8192 requests...
Completing query batches: 100%
Completed requests
===== DaCapo 23.9-RC3-chopin spring PASSED in 4029 msec =====
===== DaCapo simple tail latency: 50% 11916 usec, 90% 231060 usec, 99% 312244 usec, 99.9% 435579 usec, 99.99% 613075 usec, max 613075 usec, measured over 8192 events =====
===== DaCapo metered tail latency: 50% 11916 usec, 90% 231060 usec, 99% 312244 usec, 99.9% 435579 usec, 99.99% 613075 usec, max 613075 usec, measured over 8192 events =====
Validation FAILED for spring default
```

**Comment by mo-beck** [comment]
Hello @heshpdx  - can you please try with -XX:-UseLSE? Thanks.

**Comment by heshpdx** [comment]
Hi Monica! I just tried with `-XX:-UseLSE` and it did not change the behavior.  It keeps sending the image back to us. I tried two different JVM versions.

`Unexpected response length. Got 528 but expected 507 for request GET /resources/images/favicon.png, got:`

**Comment by caizixian** [comment]
What about `-Xint`, just to see whether it's a compiler problem?

**Comment by caizixian** [comment]
Similarly, try `-XX:+UseEpsilonGC` and give it a very large heap to rule out heap corruption?

**Comment by steveblackburn** [comment]
> I saw a different issue on AMD EPYC 9534

I was unable to reproduce this issue with 100 invocations of the same command on the same machine.

`/usr/lib/jvm/temurin-17-jdk-amd64/bin/java -jar dacapo-23.9-RC3-chopin.jar -n 2 -preserve spring`

However, I did notice a race condition on the code that outputs status.   The race is improbable, but will become more likely as the core count goes up.

I addressed this in 636d806.

The original problem remains, apparently (I am not able to reproduce it and the fix in 636d806 is unrelated).

**Comment by steveblackburn** [comment]
Looking at the original issue...

The log file provided at the start of this issue shows:

* 822 instances of `Unexpected response length`
  * 421 (51%) were `Got 528 but expected 507 for request GET /resources/images/favicon.png`
  * 396 (48%) were `Got 67721 but expected 64928 for request GET /resources/images/pets.png`
  * 1 (<1%) was `Got 4269 but expected 4261 for request GET /owners/195`
  * 1 (<1%) was `Got 5419 but expected 5411 for request GET /owners?lastName=Ortiz`

The first 8192 requests of [requests.txt](https://github.com/dacapobench/dacapobench/blob/main/benchmarks/bms/spring/workload/requests.txt) constitute the requests for this (default size) workload:
* 8192 requests
  * 923 (11.3%) `G/resources/images/favicon.png`
  * 857  (10.5%) `G/resources/images/pets.png`
  * 1 (<<1%) `G/owners/195`
  * 2 (<<1%) `G/owners?lastName=Ortiz`
* The data there also confirms that the `expected` values seen in the log file are correct for the respective requests (i.e. it is not the case that somehow the expected length had become corrupted). 
 
So about 10% of requests are reporting errors (822/8192), and of them, just four specific request types are failing and of these the main ones are failing about 45% of the time (421/923 and 396/857).  When they do fail, they fail in exactly the same way.

Also, there are no requests in the requests.txt file that have lengths `67721` (pets), `528` (favicon), or `5419` (Ortiz), but there are many request that have lengths `4269` (195).  So while it is possible that getting requests and (valid) responses might account for 1 of the 822 errors, the other 821 errors have messages with lengths that can't be attributed to other requests.

This suggests that the **failure rate for requests is around 50% in the failing execution**.  So apparently under the 'right' circumstances, this is not a corner case, but the dominant case.

The code that is printing out the error messages is [here](https://github.com/dacapobench/dacapobench/blob/main/benchmarks/bms/spring/src/org/dacapo/spring/Client.java#L130); it's part of the DaCapo harness.

I also inspected the images that were received (contained in the log file):
* I compared favicon.png file with the original, and found that the corruption was interesting for example:
   * `3f 50 4e 47 0a 1a 0a 00  00 00 0a 49 48 44 52 00   |?PNG.......IHDR.|` (original)
   * `89 50 4e 47 0d 0a 1a 0a  00 00 00 0d 49 48 44 52   |.PNG........IHDR|` (corrupted)
* All of the images I inspected (about 10), had exactly the same bit pattern --- ie the exact same corruption was present, suggesting that the source file was corrupted, rather than corruption in transmission.
* I compared the pets.png and found similar corruption.  *However*, this file contained a block of 2303 ASCII characters (embedded xml), and notably this was entirely uncorrupted, roughly 50% of bytes elsewhere being corrupted.   This presumably tells us something about the nature of the corruption.  For example:
  *  `<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c111 79.158325, 2015/09/10-01:10:20        ">` (original) 
   * `<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c111 79.158325, 2015/09/10-01:10:20        "> ` (corrupted)

**Comment by steveblackburn** [comment]
Could this conceivably be a locale issue?  It is as though some bytes are being translated, others passing through, but all in a very deterministic way.

**Comment by steveblackburn** [comment]
@heshpdx I've pushed some changes that may help us debug this.   Could you please check out 0dfc08b?

The main things it does be more graceful on port assignment (and allow the port to be specified at the command line), and adds some info to the error messages that may help us with this bug.

We still cannot reproduce it.

It would be great if you could try to reproduce the bug with 0dfc08b, and specifically:
* Try `-Xint` on the hypothesis that maybe this may be a compiler bug
* Try `-XX:+UseEpsilonGC` with a very large heap on the hypothesis that this may be a GC bug.

I'm running out of ideas here...

**Comment by heshpdx** [comment]
Thanks. Is there a jar file I can download? I'm not set to to build...

**Comment by steveblackburn** [comment]
OK, I've made a zip for you here which just contains spring at 54b987c6 here: https://drive.google.com/file/d/1KZx5x-qF3YySEG8QctQTrXfvLlG4GwkV/view?usp=sharing

I'll delete the zip once you're done with it.

**Comment by heshpdx** [comment]
Thanks, I took it out for a spin.

Baseline run: `$ ../JAVA/jdk-17.0.8.1+1/bin/java -jar dacapo-evaluation-git-54b987c6.jar spring`, still fails.

Then added: `-XX:+UnlockExperimentalVMOptions -XX:+UseEpsilonGC`, still fails.

Then added huge heap: `-Xms51200m -Xmx102400m -XX:+UnlockExperimentalVMOptions -XX:+UseEpsilonGC`, still fails.

Then instead tried `-Xint`, and it took longer but still fails:

```
===== DaCapo evaluation-git-54b987c6 spring starting =====
Starting 8192 requests...
Completing query batches: 0%^MCompleting query batches: 5%^MCompleting query batches: 10%^^MCompleting query batches: 15%^MUnexpected response length. Thread-92 got 528 but expected 507 for request 896: GET /resources/images/favicon.png, got:
?PNG
```

Then I tried the java installed on the system, which is `openjdk 11.0.20.1 2023-08-24`. Each of the above commands also fails same way.

Sorry for the bad news...

[updated comment with correct cmdline... I was indeed using the new jar file]

**Comment by steveblackburn** [comment]
Thanks for that.

I wasn't expecting it to work (I haven't attempted a fix yet, still trying to identify the source of the problem).  So this outcome is not surprising, but it does eliminate some possibilities.

Would you be able send a complete log, like you did at the start of this issue?  The extra information I added to the error messages should give us some clues as to how the corruption is arising.

Thanks.

**Comment by caizixian** [comment]
It seems to be a bug in 
https://github.com/dacapobench/dacapobench/blob/2fd1dab9d34adc5acb4f53681fddd2f90b04cdea/benchmarks/bms/spring/src/org/dacapo/spring/Client.java#L147

Reading binary data as text is not sound. And the `BufferedReader.readLine` behaviour depends on the system locale.

I can reproduce the problem by setting `LANG` to `en_US.ISO-8859-1` instead of the default `en_US.UTF-8`.

**Comment by caizixian** [comment]
We couldn't reproduce this issue before presumably because the response checksums were generated on the same configuration as the configuration we run the benchmark on.

**Comment by steveblackburn** [comment]
> Could this conceivably be a locale issue? It is as though some bytes are being translated, others passing through, but all in a very deterministic way.

So apparently this was the case.   I'll create a fix.

**Comment by steveblackburn** [comment]
I've pushed a fix in 45236345.  The checksum is now based on the raw byte array, avoiding the conversion to String which was likely the cause of this issue.  If the workload was run with a non-default locale, then the conversion to String from bytes would vary for certain byte values (which were evident in image files, but not plain text).

@heshpdx I have created a zip for you.   Can you please confirm that this addresses the issue?

https://drive.google.com/file/d/1dxE_eXqdQGzasAPDikX8wrUl-j-FjH-y/view?usp=sharing

**Comment by heshpdx** [comment]
It's better now! It changed from a run error to a verification error. Here is the output:

```
===== DaCapo evaluation-git-45236345 spring starting =====
Starting 8192 requests...
Unexpected response length. Thread-201 got 4269 but expected 4263 for request 316: GET /owners/195, got:
<!DOCTYPE html>

<html>

<head>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="shortcut icon" type="image/x-icon" href="/resources/images/favicon.png">

  <title>PetClinic :: a Spring Framework demonstration</title>

  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  <link href="/webjars/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="/resources/css/petclinic.css" />

</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark" role="navigation">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><span></span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs
Unexpected response length. Thread-170 got 5607 but expected 5601 for request 6368: GET /owners?lastName=Rivera, got:
<!DOCTYPE html>
```
[about 10 of those in a row...]
```
<html>

<head>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="shortcut icon" type="image/x-icon" href="/resources/images/favicon.png">

  <title>PetClinic :: a Spring Framework demonstration</title>

  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  <link href="/webjars/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="/resources/css/petclinic.css" />

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark" role="navigation">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"><span></span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs
Completing query batches: 100%
Completed requests
Digest validation failed for stderr.log, expecting 0xe65fccd0bbdf049d4cdba6874f799514055d30b3 found 0x51fccdbb2c8e33fb367c039c5744bc97b7f9d0af
===== DaCapo evaluation-git-45236345 spring FAILED =====
===== DaCapo simple tail latency: 50% 27368 usec, 90% 1754945 usec, 99% 2328806 usec, 99.9% 3564839 usec, 99.99% 4209524 usec, max 4209524 usec, measured over 8192 events =====
===== DaCapo metered tail latency: 50% 622086 usec, 90% 2112634 usec, 99% 3218373 usec, 99.9% 3734620 usec, 99.99% 4530233 usec, max 4530233 usec, measured over 8192 events =====
Validation FAILED for spring default

```

**Comment by heshpdx** [comment]
Actually there are seven errors, and they are reproducible. Grepping stderr, I see these:

```
Unexpected response length. Thread-22 got 4269 but expected 4263 for request 316: GET /owners/195, got:
Unexpected response length. Thread-16 got 5419 but expected 5413 for request 2492: GET /owners?lastName=Ortiz, got:
Unexpected response length. Thread-20 got 5162 but expected 5156 for request 4210: GET /owners/2023, got:
Unexpected response length. Thread-75 got 5607 but expected 5601 for request 4068: GET /owners?lastName=Rivera, got:
Unexpected response length. Thread-76 got 5419 but expected 5413 for request 4492: GET /owners?lastName=Ortiz, got:
Unexpected response length. Thread-157 got 5607 but expected 5601 for request 4295: GET /owners?lastName=Rivera, got:
Unexpected response length. Thread-103 got 5607 but expected 5601 for request 6368: GET /owners?lastName=Rivera, got:
```

Lowering the thread count doesn't change the result.

**Comment by steveblackburn** [comment]
Interesting.  These still look like locale issues, but the origin of the problem is a different one.  ~~I think those request relate to names (Ortiz, Rivera, etc) whose records include non-ascii characters.~~  They don't contain unicode characters ([data here](https://raw.githubusercontent.com/dacapobench/dacapobench/main/benchmarks/bms/spring/workload/data.sql)).  I'll continue investigating.

**Comment by caizixian** [comment]
culprit found

![image](https://github.com/dacapobench/dacapobench/assets/2891235/01a4ce3f-9d47-4329-aa10-cbd6cc34ab7a)

**Comment by caizixian** [comment]
`INSERT INTO pets VALUES (282, 'Doggon’', '2021-08-27', 4, 195);`

**Comment by caizixian** [comment]
springboot has `spring.datasource.sqlScriptEncoding= # a charset for reading SQL scripts`, which by default is the platform encoding.

**Comment by steveblackburn** [comment]
Thanks for that.  That was indeed the remaining issue.  The specific property you mention is depreciated, but the fix is trivial.

45236345
```
$ LANG=en_US.ISO-8559-1 /usr/lib/jvm/java-17-openjdk-amd64/bin/java -Xmx$h -jar dacapo-evaluation-git-45236345.jar spring

[...]
 
===== DaCapo evaluation-git-45236345 spring starting =====
Starting 8192 requests...
Unexpected response length. Thread-21 got 4269 but expected 4263 for request 316: GET /owners/195, got:
<!DOCTYPE html>

<html>

<head>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
```

dc6c6b68
```
$ LANG=en_US.ISO-8559-1 /usr/lib/jvm/java-17-openjdk-amd64/bin/java -Xmx$h -jar dacapo-evaluation-git-dc6c6b68.jar spring

[...]

===== DaCapo evaluation-git-dc6c6b68 spring starting =====
Starting 8192 requests...
Completing query batches: 100%
Completed requests
===== DaCapo evaluation-git-dc6c6b68 spring PASSED in 7450 msec =====
===== DaCapo simple tail latency: 50% 14408 usec, 90% 37381 usec, 99% 108790 usec, 99.9% 827114 usec, 99.99% 1069877 usec, max 1069877 usec, measured over 8192 events =====
===== DaCapo metered tail latency: 50% 813694 usec, 90% 1097439 usec, 99% 1137492 usec, 99.9% 1187283 usec, 99.99% 1210449 usec, max 1210449 usec, measured over 8192 events =====
```
